import { z } from "zod";

const iconKeys = [
'ShoppingCartIcon',
'UtensilsIcon',
'HomeIcon',
'CarIcon',
'PlaneIcon',
'HeartPulseIcon',
'GraduationCapIcon',
'SmartphoneIcon',
'TvIcon',
'WifiIcon',
'DropletIcon',
'FlameIcon',
'BatteryChargingIcon',
'PiggyBankIcon',
'BanknoteIcon',
'CreditCardIcon',
'BriefcaseIcon',
'ShirtIcon',
'BrushIcon',
'GiftIcon',
'AppleIcon',
'DumbbellIcon',
'ShieldCheckIcon',
'WrenchIcon',
'LandmarkIcon',
'BadgeDollarSignIcon',
'WalletIcon',
'CoinsIcon',
'TrendingUpIcon',
'BuildingIcon',
'HandCoinsIcon',
'DollarSignIcon',
'UserCheckIcon',
'ReceiptIcon',
'HandshakeIcon',
'CalendarCheckIcon',
'UserIcon',
'BookOpenIcon',
'LaptopIcon',
'MusicIcon',
'CameraIcon',
'GamepadIcon',
'HeartIcon',
'StoreIcon',
  ] as const;

export const CategorySchema = z.object({
name: z.string().min(1, "Name is required"),
Icon: z.enum(iconKeys),
});
