import { columns, Payment } from "./columns";
import { DataTable } from "./data-table";

async function getData(): Promise<Payment[]> {
  // Fetch data from your API here.
  return [
  {
    id: "txn001",
    amount: 120.75,
    category: "Food",
    description: "Purchased weekly grocery items including vegetables, fruits, and soft beverages for home use.",
    type: "Expense",
    date: "2025-07-01",
  },
  {
    id: "txn002",
    amount: 2500.0,
    category: "Salary",
    description: "Monthly salary credited from full-time employment with all applicable deductions and allowances.",
    type: "Income",
    date: "2025-07-01",
  },
  {
    id: "txn003",
    amount: 89.5,
    category: "Transport",
    description: "Filled up gas and paid for highway toll charges during the weekend trip to another city.",
    type: "Expense",
    date: "2025-07-02",
  },
  {
    id: "txn004",
    amount: 150.0,
    category: "Freelance",
    description: "Received payment for completing a landing page design project for a client via Upwork.",
    type: "Income",
    date: "2025-07-02",
  },
  {
    id: "txn005",
    amount: 30.99,
    category: "Entertainment",
    description: "Monthly Netflix subscription and one-time movie rental for a recent release.",
    type: "Expense",
    date: "2025-07-03",
  },
  {
    id: "txn006",
    amount: 74.25,
    category: "Shopping",
    description: "Bought new gym wear, shoes, and accessories during a flash sale at the mall.",
    type: "Expense",
    date: "2025-07-03",
  },
  {
    id: "txn007",
    amount: 100.0,
    category: "Gift",
    description: "Received a birthday gift fund from a family member via PayPal transfer.",
    type: "Income",
    date: "2025-07-04",
  },
  {
    id: "txn008",
    amount: 40.0,
    category: "Health",
    description: "Paid for consultation and minor prescriptions at the local pharmacy and clinic.",
    type: "Expense",
    date: "2025-07-04",
  },
  {
    id: "txn009",
    amount: 320.0,
    category: "Business",
    description: "Profit earned from online sales of custom merchandise through the Shopify store.",
    type: "Income",
    date: "2025-07-05",
  },
  {
    id: "txn010",
    amount: 65.5,
    category: "Education",
    description: "Bought a React.js eBook, tutorials, and paid for a coding platform subscription.",
    type: "Expense",
    date: "2025-07-05",
  },
  {
    id: "txn011",
    amount: 400.0,
    category: "Freelance",
    description: "Completed a full-stack development gig for a startup client including testing and deployment.",
    type: "Income",
    date: "2025-07-06",
  },
  {
    id: "txn012",
    amount: 99.9,
    category: "Home and Rentals",
    description: "Paid for monthly utilities including water, internet, and shared apartment electricity bills.",
    type: "Expense",
    date: "2025-07-06",
  },
  {
    id: "txn013",
    amount: 55.0,
    category: "Transport",
    description: "Uber trips to and from weekend training ground plus fuel top-up for scooter.",
    type: "Expense",
    date: "2025-07-07",
  },
  {
    id: "txn014",
    amount: 200.0,
    category: "Bonus",
    description: "Quarterly performance bonus for exceeding monthly targets and achieving client KPIs.",
    type: "Income",
    date: "2025-07-07",
  },
  {
    id: "txn015",
    amount: 20.0,
    category: "Food",
    description: "Quick lunch from Subway including sandwich, drink, and snacks after gym session.",
    type: "Expense",
    date: "2025-07-08",
  },
  {
    id: "txn016",
    amount: 85.75,
    category: "Shopping",
    description: "Purchased everyday essentials including toiletries, laundry supplies, and household goods.",
    type: "Expense",
    date: "2025-07-08",
  },
  {
    id: "txn017",
    amount: 35.99,
    category: "Health",
    description: "Bought vitamins, protein supplements, and over-the-counter medications for recovery.",
    type: "Expense",
    date: "2025-07-09",
  },
  {
    id: "txn018",
    amount: 2900.0,
    category: "Salary",
    description: "Direct deposit from company payroll for the month of July including remote allowance.",
    type: "Income",
    date: "2025-07-09",
  },
  {
    id: "txn019",
    amount: 15.0,
    category: "Entertainment",
    description: "Subscribed to Spotify Premium and purchased one mobile game app for leisure.",
    type: "Expense",
    date: "2025-07-10",
  },
  {
    id: "txn020",
    amount: 500.0,
    category: "Business",
    description: "Profit from reselling limited edition sneakers via online marketplaces.",
    type: "Income",
    date: "2025-07-10",
  },
  {
    id: "txn021",
    amount: 59.5,
    category: "Home and Rentals",
    description: "Paid service charge and monthly maintenance fees for shared apartment amenities.",
    type: "Expense",
    date: "2025-07-11",
  },
  {
    id: "txn022",
    amount: 17.89,
    category: "Food",
    description: "Evening meal including grilled chicken, rice, and bottled fruit juice from local diner.",
    type: "Expense",
    date: "2025-07-11",
  },
  {
    id: "txn023",
    amount: 190.0,
    category: "Freelance",
    description: "Earned from designing a UI kit and landing page using Figma and Framer for a client.",
    type: "Income",
    date: "2025-07-12",
  },
  {
    id: "txn024",
    amount: 21.25,
    category: "Transport",
    description: "Paid public bus tickets and short-distance Uber fares within the city center.",
    type: "Expense",
    date: "2025-07-12",
  },
  {
    id: "txn025",
    amount: 110.0,
    category: "Gift",
    description: "Received cash gift from a friend during holiday celebrations and festive gathering.",
    type: "Income",
    date: "2025-07-13",
  },
  {
    id: "txn026",
    amount: 38.4,
    category: "Shopping",
    description: "Ordered a new backpack and basic supplies from Amazon Prime Deals Week.",
    type: "Expense",
    date: "2025-07-13",
  },
  {
    id: "txn027",
    amount: 25.99,
    category: "Health",
    description: "Paid for monthly gym membership renewal and physical therapy session.",
    type: "Expense",
    date: "2025-07-14",
  },
  {
    id: "txn028",
    amount: 78.9,
    category: "Education",
    description: "Paid for Udemy course on advanced TypeScript with bonus practice projects.",
    type: "Expense",
    date: "2025-07-14",
  },
  {
    id: "txn029",
    amount: 2450.0,
    category: "Salary",
    description: "Full-time income deposited to RBC account with automatic deductions and tax applied.",
    type: "Income",
    date: "2025-07-15",
  },
  {
    id: "txn030",
    amount: 18.75,
    category: "Food",
    description: "Late-night takeout including pizza, wings, and a can of soda with delivery fee.",
    type: "Expense",
    date: "2025-07-15",
  },
];
}

export default async function DemoPage() {
  const data = await getData();

  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  );
}
